meta_product_name: "Buddylingua"
meta_title: "Buddylingua - Meet a buddy, learn a language."
meta_description: "Get started with your language journey today"
meta_image: "meta.png" # should exist in `app/assets/images/`

